[2024-05-02T22:59:58.731+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T22:59:58.952+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 17_dag_buah.tambah_data_buah manual__2024-05-02T22:57:18.407944+00:00 [queued]>
[2024-05-02T22:59:59.000+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 17_dag_buah.tambah_data_buah manual__2024-05-02T22:57:18.407944+00:00 [queued]>
[2024-05-02T22:59:59.006+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-02T22:59:59.122+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): tambah_data_buah> on 2024-05-02 22:57:18.407944+00:00
[2024-05-02T22:59:59.156+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=410) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-02T22:59:59.166+0000] {standard_task_runner.py:63} INFO - Started process 425 to run task
[2024-05-02T22:59:59.185+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '17_dag_buah', 'tambah_data_buah', 'manual__2024-05-02T22:57:18.407944+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/17_DAG_eks.py', '--cfg-path', '/tmp/tmpim2xx3zr']
[2024-05-02T22:59:59.209+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask tambah_data_buah
[2024-05-02T22:59:59.621+0000] {task_command.py:426} INFO - Running <TaskInstance: 17_dag_buah.tambah_data_buah manual__2024-05-02T22:57:18.407944+00:00 [running]> on host bb10af88434b
[2024-05-02T23:00:00.452+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ERISTA' AIRFLOW_CTX_DAG_ID='17_dag_buah' AIRFLOW_CTX_TASK_ID='tambah_data_buah' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T22:57:18.407944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T22:57:18.407944+00:00'
[2024-05-02T23:00:00.468+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T23:00:00.580+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-02T23:00:00.665+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-02T23:00:00.667+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T23:00:00.696+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=17_dag_buah, task_id=tambah_data_buah, execution_date=20240502T225718, start_date=20240502T225958, end_date=20240502T230000
[2024-05-02T23:00:00.802+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-02T23:00:00.923+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T23:00:00.956+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
